"""创作大纲（creative_plans）常量。"""

from app.core.clarification_constants import CREATION_TYPE_NOVEL, CREATION_TYPE_VIDEO

# 大纲状态机
PLAN_STATUS_DRAFTING = "drafting"
PLAN_STATUS_AWAITING_REVIEW = "awaiting_review"
PLAN_STATUS_APPROVED = "approved"
PLAN_STATUS_SUPERSEDED = "superseded"

# 配置默认值
DEFAULT_OUTLINE_ENABLED = True
DEFAULT_OUTLINE_REQUIRES_CLARIFICATION = True
DEFAULT_OUTLINE_AUTO_APPROVE = False
DEFAULT_OUTLINE_MAX_REVISIONS = 10

# 创作类型（引用澄清层权威）
OUTLINE_CREATION_TYPE_NOVEL = CREATION_TYPE_NOVEL
OUTLINE_CREATION_TYPE_VIDEO = CREATION_TYPE_VIDEO

# 版本号起点
PLAN_INITIAL_VERSION = 1
